In [7]:
##q1
import numpy as np 
##arr=np.array([0,1,2,3,4,5,6,7,8])
##arr1=np.arange(arr).reshape(3,3)
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
##q2
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
result=np.where(arr%2!=0,-1,arr)
print(result)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [13]:
##q3
import numpy as np
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
greater_array=np.where(x>y)
print(greater_array)
equal_array=np.where(x==y)
print(equal_array)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [49]:
##q4
import numpy as np
arr=np.arange(100).reshape(5,-1)
##final=np.where(arr(5,4))
print(arr[:,:4])

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [66]:
##q1_additional_questions
import numpy as np
array = np.random.randint(30, 41, size=10)
print(array)

[30 39 39 32 40 30 38 40 37 30]


In [88]:
import numpy as np
A=np.array([(1,2,3),(4,5,6),(7,8,10)])
B=np.array([(7,8,10),(4,5,6),(1,2,3)])
C=A+B
E=A-B

SumA=np.sum(A)
SumB=np.sum(B,axis=0)
SumC=np.sum(C,axis=1)

D = np.matmul(A, B)
E = np.sort(E)
transE=E.T



print("the addition is \n ",C)
print("the substraction is \n",E)
print("the sum of the matrix a is \t",SumA)
print("the sum of the columns of the b matrix is \n",SumB)
print("the sum of the columns of the c matrix is \n",SumC)
print("the multipication of the D matrix is \n",D)
print("the transpose of the E matrix is \n ",transE)

the addition is 
  [[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]
the substraction is 
 [[-7 -6 -6]
 [ 0  0  0]
 [ 6  6  7]]
the sum of the matrix a is 	 46
the sum of the columns of the b matrix is 
 [12 15 19]
the sum of the columns of the c matrix is 
 [31 30 31]
the multipication of the D matrix is 
 [[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]
the transpose of the E matrix is 
  [[-7  0  6]
 [-6  0  6]
 [-6  0  7]]


In [90]:
import csv 
with open('/home/student/Desktop/data.csv','rt')as f:
    data=csv.reader(f)
    for row in data:
        print(row)


['prog languages ; designed by ; abcd;']
['hello world']
['india usa ']
['jaava python']


NameError: name 'reader' is not defined

In [95]:
import csv 
reader=csv.DictReader(open('/home/student/Desktop/data.csv','rt'))
for raw in reader:
    print(raw)

OrderedDict([('prog languages ; designed by ; abcd;', 'hello world')])
OrderedDict([('prog languages ; designed by ; abcd;', 'india usa ')])
OrderedDict([('prog languages ; designed by ; abcd;', 'jaava python')])
